# Generated by Django 3.0 on 2021-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eage', models.IntegerField()),
                ('eusname', models.CharField(max_length=120)),
                ('epwd', models.CharField(max_length=120)),
                ('eemail', models.EmailField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
