# Generated by Django 3.0 on 2021-10-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbtitle', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.TextField(max_length=200)),
                ('crs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eapp.CourseCategory')),
            ],
        ),
    ]
